- name: ensure apt cache is up to date
  apt: update_cache=yes
- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - postgresql
      - libpq-dev
      - python3-psycopg2

- name: ensure database is created
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
