---
- hosts: all
  become: yes # This means that all tasks will be executed with sudo
  vars:
    venv_path: "/home/vagrant/venv"
    requirements_path: "/vagrant/requirements.txt"
    dbname: test_db
    dbuser: test_db
    dbpassword: test_db
  roles:
    #- {role: python}
    - {role: postgresql}